FROM centos:latest
ENV JAVA_HOME /opt/java/jdk1.8.0_261
ENV PATH ${PATH}:${JAVA_HOME}/bin

COPY CPUAndMemory.class .
COPY jdk-8u261-linux-x64.tar.gz .

RUN tar -zxvf jdk-8u261-linux-x64.tar.gz \
    && rm -f jdk-8u261-linux-x64.tar.gz \
    && mkdir -p /opt/java \
    && mv jdk1.8.0_261 /opt/java/.

CMD ["/opt/java/jdk1.8.0_261/bin/java", "CPUAndMemory"]
